### ISSUE TITLE
methods not defined

### ISSUE THREAD

**Issue by lllama** [rlidwka/iohttp#1]
When following the readme example under iojs 2.2.1, I get the error "Cannot read the property 'methods' of undefined".

I found that I needed to change the line "module.exports = HTTPParser" to "exports.HTTPParser = HTTPParser" in index.js and then things worked as expected.

(Note that I have 'installed' this by placing index.js and parser.js in an iohttp directory and requiring them).

**Comment by rlidwka** [comment]
I believe it's a mistake in README. Fixed.

**Comment by lllama** [comment]
Confirmed - updated example works. My lack of knowledge about exports vs module.exports to blame.
